scrape_book_info:
  description: >
    Find and summarize opinions from Goodreads reviews on the book: {book_title}. 
    Always include the name of the book, the author, and the Goodreads rating.
  expected_output: >
    Summaries of Goodreads reviews for the book and the links to the reviews.

interactive_qa:
  description: >
    Use the scraped information to interact with the user, answering any questions they may have about the book.
  expected_output: >
    Real-time responses to user questions about the book, based on the scraped information.
  agent: qa_agent
  allow_user_interaction: True
  async_execution: True  # Allows for continuous, asynchronous interaction
